# Generated by Django 4.2 on 2024-05-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.AddField(
            model_name='book',
            name='image_urls',
            field=models.URLField(blank=True),
        ),
        migrations.RenameModel(
            old_name='Actor',
            new_name='Author',
        ),
        migrations.DeleteModel(
            name='CastCredit',
        ),
        migrations.AddField(
            model_name='authorcredit',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.author'),
        ),
        migrations.AddField(
            model_name='authorcredit',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
    ]
